<!DOCTYPE html>
<html>
<head>
    <title>Pencapaian Akhlak</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <style type="text/css">
        table tr td,
        table tr th {
            font-size: 9pt;
        }
        .header-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 100%;
        }
        .header-container img {
            display: block;
            margin-bottom: 10px;
        }
    </style>
    <div class="header-container">
        <div>
            <img src="{{ public_path('img/logo_akhlak.png') }}" style="height: 47px; width: 120px;" />
        </div>
        {{-- <div>
            <img src="{{ public_path('img/mtc-logo-new.png') }}" style="height: 120px; width: 120px;" />
        </div> --}}
    </div>
    <table class='table table-bordered table-sm'>
        <thead>
            <tr>
                <th>User ID</th>
                <th>Nilai Akhlak</th>
                <th>Periode</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $userInfo->name }}</td>
                <td>Kompeten</td>
                <td>2022</td>
            </tr>
        </tbody>
    </table>
    <!-- Add the rest of your content here -->

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Judul Kegiatan</th>
                <th>Score</th>
                <th>Periode Start</th>
                <th>Periode End</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($pencapaian as $item)
            <tr>
                <td>{{ $item->judul_kegiatan }}</td>
                <td>{{ $item->score }} %</td>
                <td>{{ $item->periode_start }}</td>
                <td>{{ $item->periode_end }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <table class="table table-borderless mt-4">
        <tbody>
            <tr class="table-sm">
                <td class="m-0" width="200px">
                    <div class="font-weight-bold">Average Nilai Akhlak</div>
                    <div>Avg. Amanah</div>
                    <div>Avg. Kompeten</div>
                    <div>Avg. Harmonis</div>
                    <div>Avg. Loyal</div>
                    <div>Avg. Adaptif</div>
                    <div>Avg. Kolaboratif</div>
                </td>
                <td>
                    <div>&nbsp;</div>
                    <div>: 33 %</div>
                    <div>: 50 %</div>
                    <div>: 78 %</div>
                    <div>: 90 %</div>
                    <div>: 45 %</div>
                    <div>: 0 %</div>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="text-center">
        <div>
            <img src="{{ public_path('img/mtc-logo-new.png') }}" style="height: 120px; width: 120px;" />
            <p style="font-size: 12px;">Generated by Pertamina Maritime Training Center.</p>
        </div>
    </div>
</body>
</html>
